export interface VoterProfile {
  name: string;
  age: number;
  location: string;
  occupation: string;
  background: string;
  politicalLean: "Conservative" | "Progressive" | "Swinging" | "Apathetic" | "Centre" | "Centre-right" | "Centre-progressive" | "Conservative-leaning" | "Progressive-leaning" | "Greens-leaning";
  concerns: string[];
  reasoning: "Populist" | "Emotional" | "Rational" | "Tribal" | "Ideological" | "Rational / emotional" | "Emotional / ideological" | "Emotional / tribal";
  susceptibility: string[];
}

export const VOTER_POOL: VoterProfile[] = [
  {
    name: "Barry Nolan",
    age: 64,
    location: "Penrith NSW",
    occupation: "Retired electrician",
    background: "Spent 35 years on construction sites across Western Sydney. Bitter about rising energy bills. Distrusts inner-city politicians.",
    politicalLean: "Conservative",
    concerns: ["Energy costs", "Cost of living"],
    reasoning: "Populist",
    susceptibility: ["Straight-talking", "Anti-establishment rhetoric"],
  },
  {
    name: "Chloe Atkinson",
    age: 23,
    location: "Fitzroy VIC",
    occupation: "Barista / Environmental science student",
    background: "Grew up in Ballarat but moved to the inner city. Anxious about climate change and housing affordability.",
    politicalLean: "Progressive",
    concerns: ["Climate", "Housing", "LGBTQ+ rights"],
    reasoning: "Emotional",
    susceptibility: ["Values-based appeals", "Peer consensus"],
  },
  {
    name: "Minh Nguyen",
    age: 51,
    location: "Cabramatta NSW",
    occupation: "Restaurant owner",
    background: "Vietnamese-Australian refugee. Proud of his business. Worried about rising food costs and labour shortages.",
    politicalLean: "Swinging",
    concerns: ["Small business", "Immigration", "Cost of living"],
    reasoning: "Rational",
    susceptibility: ["Economic arguments", "Personal success stories"],
  },
  {
    name: "Tracey Dunbar",
    age: 38,
    location: "Townsville QLD",
    occupation: "School aide",
    background: "Single mother of three. Relies on family tax benefits. Votes for whoever seems to care about families.",
    politicalLean: "Swinging",
    concerns: ["Cost of living", "Childcare", "Schools"],
    reasoning: "Emotional",
    susceptibility: ["Relatable personal stories", "Direct family benefits"],
  },
  {
    name: "Colonel (Ret.) David Marsh",
    age: 69,
    location: "Canberra ACT",
    occupation: "Retired Army officer",
    background: "Disciplined and patriotic. Believes in strong institutions. Respects composure and authority.",
    politicalLean: "Conservative",
    concerns: ["Defence", "Border security", "Law and order"],
    reasoning: "Tribal",
    susceptibility: ["Authoritative delivery", "National security framing"],
  },
  {
    name: "Aunty Rose Napurrula",
    age: 58,
    location: "Darwin NT",
    occupation: "Indigenous community health worker",
    background: "Advocates for remote community services. Sceptical of politicians who make empty promises.",
    politicalLean: "Progressive",
    concerns: ["Indigenous health", "Remote services", "Housing"],
    reasoning: "Rational",
    susceptibility: ["Genuine acknowledgment", "Specific policy detail"],
  },
  {
    name: "Dr. Helen Fairweather",
    age: 72,
    location: "Toorak VIC",
    occupation: "Retired GP",
    background: "Wealthy and analytical. Resents populism but also high taxes. Analytical and conflicted.",
    politicalLean: "Centre",
    concerns: ["Healthcare system", "Fiscal responsibility", "Social cohesion"],
    reasoning: "Rational",
    susceptibility: ["Expert references", "Calm logical delivery"],
  },
  {
    name: "Damo Perkins",
    age: 46,
    location: "Broken Hill NSW",
    occupation: "Long-haul truckie",
    background: "Anti-establishment and convinced both major parties are rotten. Responds to raw authenticity.",
    politicalLean: "Apathetic",
    concerns: ["Fuel costs", "Regional infrastructure", "Government overreach"],
    reasoning: "Populist",
    susceptibility: ["Bluntness", "Anti-politician sentiment"],
  },
  {
    name: "Sandra Kowalski",
    age: 44,
    location: "Hobart TAS",
    occupation: "High school science teacher",
    background: "Methodical and evidence-driven. Frustrated by misinformation. Votes after researching policies.",
    politicalLean: "Centre-progressive",
    concerns: ["Education funding", "Climate", "Public services"],
    reasoning: "Rational",
    susceptibility: ["Data", "Nuanced policy", "Intellectual honesty"],
  },
  {
    name: "Jake Sorensen",
    age: 20,
    location: "Brisbane QLD",
    occupation: "Law student",
    background: "Politically engaged and very online. Impatient with older politicians. Idealistic.",
    politicalLean: "Progressive",
    concerns: ["Housing affordability", "Climate", "Student debt"],
    reasoning: "Emotional / ideological",
    susceptibility: ["Bold progressive policy", "Idealism"],
  },
  {
    name: "George Haddad",
    age: 39,
    location: "Parramatta NSW",
    occupation: "Accountant",
    background: "Second-generation Lebanese-Australian. Focused on economic stability and low taxes.",
    politicalLean: "Centre-right",
    concerns: ["Taxes", "Small business", "Family values"],
    reasoning: "Rational",
    susceptibility: ["Economic competence", "Fiscal arguments"],
  },
  {
    name: "Ken Walters",
    age: 61,
    location: "Griffith NSW",
    occupation: "Rice and cotton farmer",
    background: "Third-generation farmer. Concerned about water rights. Suspicious of greenies but pragmatic about drought.",
    politicalLean: "Conservative",
    concerns: ["Water rights", "Farming subsidies", "Regional investment"],
    reasoning: "Rational",
    susceptibility: ["Practical rural policy", "Respecting farming communities"],
  },
  {
    name: "Priya Sundaram",
    age: 34,
    location: "Whyalla SA",
    occupation: "Nurse",
    background: "Originally from Chennai. Citizen for six years. Believes the healthcare system is underfunded.",
    politicalLean: "Progressive",
    concerns: ["Healthcare funding", "Nursing wages", "Immigration pathways"],
    reasoning: "Rational",
    susceptibility: ["Healthcare policy", "Personal dignity appeals"],
  },
  {
    name: "Scott Rennie",
    age: 42,
    location: "Perth WA",
    occupation: "Real estate agent",
    background: "Benefits from high property prices but aware of housing locking out young people. Charismatic.",
    politicalLean: "Centre-right",
    concerns: ["Property market", "Interest rates", "Business confidence"],
    reasoning: "Populist",
    susceptibility: ["Confidence", "Economic optimism"],
  },
  {
    name: "Margaret Ellison",
    age: 74,
    location: "Gold Coast QLD",
    occupation: "Retired bookkeeper",
    background: "Lives off super and part pension. Fears changes to superannuation rules.",
    politicalLean: "Conservative",
    concerns: ["Superannuation", "Pension", "Cost of living"],
    reasoning: "Tribal",
    susceptibility: ["Reassurance", "Simplicity", "Trustworthiness signals"],
  },
  {
    name: "Aidan Foley",
    age: 31,
    location: "Surry Hills NSW",
    occupation: "Software engineer",
    background: "Globally minded tech worker. Pays high rent. Votes on policy substance.",
    politicalLean: "Centre-progressive",
    concerns: ["Housing", "Tech policy", "Climate", "Global competitiveness"],
    reasoning: "Rational",
    susceptibility: ["Smart policy", "International comparisons"],
  },
  {
    name: "Emmanuel Akol",
    age: 29,
    location: "Adelaide SA",
    occupation: "Youth worker",
    background: "South Sudanese-Australian refugee. Invested in how Australia treats vulnerable people.",
    politicalLean: "Progressive",
    concerns: ["Refugee policy", "Youth services", "Racial equality"],
    reasoning: "Rational",
    susceptibility: ["Genuine policy commitment", "Respect for lived experience"],
  },
  {
    name: "Craig Murchison",
    age: 53,
    location: "Dubbo NSW",
    occupation: "Pub owner",
    background: "Owns a social hub in a small town. Wants regional Australia taken seriously.",
    politicalLean: "Swinging",
    concerns: ["Regional investment", "Small business", "Roads and infrastructure"],
    reasoning: "Populist",
    susceptibility: ["Regional acknowledgment", "Relatable community values"],
  },
  {
    name: "Kylie Pemberton",
    age: 36,
    location: "Cranbourne VIC",
    occupation: "Stay-at-home parent",
    background: "Outer Melbourne resident. Mortgage is tight. Focuses on school quality and local safety.",
    politicalLean: "Swinging",
    concerns: ["Schools", "Cost of living", "Neighbourhood safety"],
    reasoning: "Emotional",
    susceptibility: ["Relatable family framing", "Local community investment"],
  },
  {
    name: "Zara Willis",
    age: 19,
    location: "Wollongong NSW",
    occupation: "Student",
    background: "First-time voter. Consumes politics via TikTok. Views shift based on viral content.",
    politicalLean: "Progressive-leaning",
    concerns: ["Climate", "Housing", "Cost of living"],
    reasoning: "Emotional",
    susceptibility: ["Charisma", "Viral-style messaging", "Personal attacks"],
  },
  {
    name: "Franco Moretti",
    age: 66,
    location: "Barossa Valley SA",
    occupation: "Winemaker",
    background: "Third-generation Barossa family. Proud of heritage. Conservative economics, progressive multiculturalism.",
    politicalLean: "Centre-right",
    concerns: ["Agriculture", "Exports", "Water", "Small business"],
    reasoning: "Emotional",
    susceptibility: ["National pride", "Economic confidence", "Regional respect"],
  },
  {
    name: "Bec Thornton",
    age: 27,
    location: "Launceston TAS",
    occupation: "Disability support worker",
    background: "Sees NDIS stretching. Lives in an expensive flat. Empathetic and thoughtful.",
    politicalLean: "Progressive",
    concerns: ["NDIS", "Disability services", "Housing", "Wages"],
    reasoning: "Rational",
    susceptibility: ["Compassionate policy detail", "Funding commitments"],
  },
  {
    name: "Phil Huang",
    age: 47,
    location: "Box Hill VIC",
    occupation: "Pharmacist",
    background: "Owns two pharmacies. Pays close attention to PBS changes. Cautious and methodical.",
    politicalLean: "Centre",
    concerns: ["Healthcare policy", "Small business", "Medicare"],
    reasoning: "Rational",
    susceptibility: ["Policy precision", "Calm authority"],
  },
  {
    name: "Lorraine Cattanach",
    age: 55,
    location: "Mackay QLD",
    occupation: "Coal mine admin",
    background: "20-year coal industry veteran. Anti-disruption. Tired of being made to feel guilty.",
    politicalLean: "Conservative",
    concerns: ["Mining jobs", "Energy transition", "Regional employment"],
    reasoning: "Emotional",
    susceptibility: ["Job security messaging", "Anti-greenie sentiment"],
  },
  {
    name: "Abdul Rahman Siddiqui",
    age: 44,
    location: "Auburn NSW",
    occupation: "Taxi driver",
    background: "Pakistani-Australian. Works long hours for family. Deeply religious and family-focused.",
    politicalLean: "Conservative-leaning",
    concerns: ["Cost of living", "Family values", "Religious freedom"],
    reasoning: "Emotional",
    susceptibility: ["Personal cost-of-living framing", "Family-first rhetoric"],
  },
  {
    name: "Natasha Brennan",
    age: 33,
    location: "Fremantle WA",
    occupation: "Marine biologist",
    background: "Passionate about ocean conservation. Articulate and confident. Unimpressed by question-dodging.",
    politicalLean: "Progressive",
    concerns: ["Climate", "Environment", "Science funding"],
    reasoning: "Rational",
    susceptibility: ["Evidence-based policy", "Intellectual rigour"],
  },
  {
    name: "Terry Scullin",
    age: 59,
    location: "Geelong VIC",
    occupation: "Logistics worker",
    background: "Former Ford worker. Feels left behind by globalisation. Drawn to anti-immigration arguments.",
    politicalLean: "Swinging",
    concerns: ["Jobs", "Wages", "Manufacturing", "Immigration"],
    reasoning: "Tribal",
    susceptibility: ["Nostalgia", "Economic protectionism", "Mate-culture appeals"],
  },
  {
    name: "Jasmine Lee",
    age: 25,
    location: "Fortitude Valley QLD",
    occupation: "Graphic designer",
    background: "Renting and saving nothing. Identifies with generational economic disadvantage. Vocal online.",
    politicalLean: "Progressive",
    concerns: ["Housing", "Intergenerational equity", "Climate"],
    reasoning: "Emotional",
    susceptibility: ["Generational fairness arguments", "Negative gearing critique"],
  },
  {
    name: "Bob Stafford",
    age: 77,
    location: "Ballarat VIC",
    occupation: "Retired bank manager",
    background: "Moderate who has drifted right. Responds to dignity and courtesy. analytical.",
    politicalLean: "Centre-right",
    concerns: ["Pension", "Aged care", "Social stability"],
    reasoning: "Rational",
    susceptibility: ["Respectful tone", "Personal composure", "Reassurance"],
  },
  {
    name: "Amelia Watson",
    age: 30,
    location: "Alice Springs NT",
    occupation: "Paramedic",
    background: "Deals with inadequate social services. Committed but burned out. Hard to fool.",
    politicalLean: "Progressive",
    concerns: ["Remote healthcare", "Housing", "Indigenous services"],
    reasoning: "Rational",
    susceptibility: ["Specific funding commitments", "Practical on-the-ground policy"],
  },
  {
    name: "Reg Hollingsworth",
    age: 68,
    location: "Bathurst NSW",
    occupation: "Retired public servant",
    background: "Believes in bureaucratic process. Fiscally conservative. Wants to see costings.",
    politicalLean: "Centre",
    concerns: ["Fiscal responsibility", "Public services", "Government accountability"],
    reasoning: "Rational",
    susceptibility: ["Detailed policy", "Budget responsibility framing"],
  },
  {
    name: "Mei-Ling Zhang",
    age: 38,
    location: "Chatswood NSW",
    occupation: "Accountant",
    background: "Migrated from China 12 years ago. Focused on kids' education and saving. Pays attention to tax.",
    politicalLean: "Centre",
    concerns: ["Education", "Taxes", "Property", "Immigration"],
    reasoning: "Rational",
    susceptibility: ["Economic competence", "Multicultural acknowledgment"],
  },
  {
    name: "Shaun Daly",
    age: 22,
    location: "Cairns QLD",
    occupation: "Hostel worker",
    background: "Loves the reef and lifestyle. Hates corporate development. Environmentalist.",
    politicalLean: "Progressive",
    concerns: ["Environment", "Reef", "Tourism"],
    reasoning: "Emotional",
    susceptibility: ["Passion", "Environmental urgency", "Anti-corporate messaging"],
  },
  {
    name: "Helen Trujillo",
    age: 49,
    location: "Dandenong VIC",
    occupation: "Social worker",
    background: "Colombian-Australian. Sees poverty and breakdown. Hard to fool.",
    politicalLean: "Progressive",
    concerns: ["Social services", "Family violence", "Housing", "Immigration"],
    reasoning: "Rational",
    susceptibility: ["Genuine compassion", "Specific funding policy"],
  },
  {
    name: "Greg Papadopoulos",
    age: 57,
    location: "Oakleigh VIC",
    occupation: "Building contractor",
    background: "Done well in construction boom. Socially conservative. Employs 12 people.",
    politicalLean: "Conservative",
    concerns: ["Construction industry", "Wages", "Business costs", "Immigration"],
    reasoning: "Rational",
    susceptibility: ["Economic confidence", "Business-friendly framing"],
  },
  {
    name: "Tanya Gorman",
    age: 45,
    location: "Darwin NT",
    occupation: "Government administrator",
    background: "Navigates NT political landscape. Pragmatic and culturally aware. Votes for competence.",
    politicalLean: "Centre",
    concerns: ["Remote services", "Indigenous policy", "Territory funding"],
    reasoning: "Rational",
    susceptibility: ["Demonstrated knowledge of NT issues", "Practical solutions"],
  },
  {
    name: "Oliver Nguyen",
    age: 18,
    location: "Doncaster VIC",
    occupation: "Student",
    background: "First-time voter. Son of immigrants. Idealistic but swayed by certainty.",
    politicalLean: "Progressive-leaning",
    concerns: ["Climate", "Education", "Housing"],
    reasoning: "Emotional",
    susceptibility: ["Youth-focused policy", "Charisma", "Optimism"],
  },
  {
    name: "Ruth Andersen",
    age: 62,
    location: "Mornington Peninsula VIC",
    occupation: "Semi-retired principal",
    background: "Progressive on education, fiscally conservative. Reads widely and thinks for herself.",
    politicalLean: "Centre",
    concerns: ["Education", "Aged care", "Environment"],
    reasoning: "Rational",
    susceptibility: ["Substance over style", "Respectful delivery"],
  },
  {
    name: "Steve Nakamura",
    age: 35,
    location: "Sunshine Coast QLD",
    occupation: "Surf instructor / Tradesman",
    background: "Disengaged until floods hit. Newly radicalised on climate policy. Easygoing.",
    politicalLean: "Swinging",
    concerns: ["Climate", "Disaster preparedness", "Cost of living"],
    reasoning: "Emotional",
    susceptibility: ["Climate urgency", "Personal impact stories"],
  },
  {
    name: "Patricia O'Brien",
    age: 71,
    location: "Wagga Wagga NSW",
    occupation: "Retired Catholic teacher",
    background: "Lives by faith and routine. Loyal conservative. Dislikes cruelty or profanity.",
    politicalLean: "Conservative",
    concerns: ["Religious freedom", "Education", "Family values", "Aged care"],
    reasoning: "Tribal",
    susceptibility: ["Values language", "Decency framing"],
  },
  {
    name: "Isaac Mwangi",
    age: 32,
    location: "Footscray VIC",
    occupation: "Electrician",
    background: "Kenyan-Australian. Proud of the life he built. Wants rewards for hard work.",
    politicalLean: "Swinging",
    concerns: ["Immigration pathways", "Cost of living", "Trades recognition"],
    reasoning: "Rational",
    susceptibility: ["Fairness arguments", "Personal aspiration messaging"],
  },
  {
    name: "Sharon Koloamatangi",
    age: 40,
    location: "Mount Druitt NSW",
    occupation: "Community nurse",
    background: "Samoan-Australian. Rooted in church and community. Advocates for the voiceless.",
    politicalLean: "Progressive",
    concerns: ["Community health", "Housing", "Pacific Islander issues"],
    reasoning: "Emotional",
    susceptibility: ["Community-level framing", "Empathy and dignity appeals"],
  },
  {
    name: "Neil Patterson",
    age: 54,
    location: "Toowoomba QLD",
    occupation: "Ag equipment dealer",
    background: "Business tied to farmers. Fiscally conservative. Zero tolerance for urban politicians.",
    politicalLean: "Conservative",
    concerns: ["Agriculture", "Fuel costs", "Regional services", "Water"],
    reasoning: "Rational",
    susceptibility: ["Rural credibility", "Economic arguments for regional investment"],
  },
  {
    name: "Leila Hosseini",
    age: 28,
    location: "Docklands VIC",
    occupation: "Architecture graduate",
    background: "Iranian-Australian. Designs public housing. Grateful but frustrated by property wealth barriers.",
    politicalLean: "Progressive",
    concerns: ["Housing", "Immigration policy", "Urban planning"],
    reasoning: "Rational",
    susceptibility: ["Housing policy depth", "Multicultural acknowledgment"],
  },
  {
    name: "Murray Blackwood",
    age: 60,
    location: "Kalgoorlie WA",
    occupation: "Gold miner / FIFO veteran",
    background: "25-year FIFO veteran. Feels city people don't respect the resources industry.",
    politicalLean: "Conservative",
    concerns: ["Mining industry", "FIFO conditions", "Resources policy"],
    reasoning: "Tribal",
    susceptibility: ["Resources industry respect", "Anti-green energy sentiment"],
  },
  {
    name: "Fiona Castle",
    age: 37,
    location: "Newcastle NSW",
    occupation: "Solar panel installer",
    background: "Former coal worker. Lived the energy transition. Measured and credible.",
    politicalLean: "Swinging",
    concerns: ["Energy transition", "Retraining", "Job security"],
    reasoning: "Rational",
    susceptibility: ["Just transition policy", "Practical economic detail"],
  },
  {
    name: "Tom Delacroix",
    age: 26,
    location: "Newtown NSW",
    occupation: "Graphic novelist",
    background: "Queer, French-Australian. Progressive social issues. Cynical about major parties.",
    politicalLean: "Greens-leaning",
    concerns: ["LGBTQ+ rights", "Climate", "Housing", "Arts funding"],
    reasoning: "Ideological",
    susceptibility: ["Social justice framing", "Anti-establishment positioning"],
  },
  {
    name: "Deborah Yuen",
    age: 52,
    location: "Canberra ACT",
    occupation: "Senior public servant",
    background: "Professionally apolitical but personally engaged. Believes in institutional integrity.",
    politicalLean: "Centre",
    concerns: ["Governance", "Accountability", "Public service integrity"],
    reasoning: "Rational",
    susceptibility: ["Institutional respect", "Policy coherence"],
  },
  {
    name: "Aaron Bullock",
    age: 41,
    location: "Logan QLD",
    occupation: "Correctional officer",
    background: "Sees cycle of poverty and crime. Frustrated by culture war politics.",
    politicalLean: "Swinging",
    concerns: ["Law and order", "Rehabilitation", "Cost of living"],
    reasoning: "Rational",
    susceptibility: ["Nuanced crime policy", "Respecting frontline workers"],
  },
  {
    name: "Wendy Broadhurst",
    age: 67,
    location: "Victor Harbor SA",
    occupation: "Retired librarian",
    background: "Cares about democracy and public discourse. Penalises liars and rudeness.",
    politicalLean: "Centre-progressive",
    concerns: ["Education", "Democracy", "Media literacy", "Aged care"],
    reasoning: "Rational",
    susceptibility: ["Intellectual honesty", "Respectful debate conduct"],
  },
  {
    name: "Danny Ruiz",
    age: 24,
    location: "Bankstown NSW",
    occupation: "Apprentice plumber",
    background: "Chilean-Australian. Starting to care about tax. Easy to impress with confidence.",
    politicalLean: "Swinging",
    concerns: ["Wages", "Trades", "Cost of living", "Taxes"],
    reasoning: "Populist",
    susceptibility: ["Charisma", "Confident delivery", "Anti-tax rhetoric"],
  },
  {
    name: "Heather Moss",
    age: 48,
    location: "Bendigo VIC",
    occupation: "Community pharmacist",
    background: "Fighting against big chains. Pragmatic centrist with no party loyalty.",
    politicalLean: "Centre",
    concerns: ["Small business", "Healthcare", "Local community"],
    reasoning: "Rational",
    susceptibility: ["Practical policy", "Local community investment"],
  },
  {
    name: "Doug Mercer",
    age: 73,
    location: "Port Augusta SA",
    occupation: "Former steelworker",
    background: "Union man his whole life. Still angry about manufacturing decline. Hard to move.",
    politicalLean: "Progressive",
    concerns: ["Manufacturing", "Unions", "Cost of living", "Aged care"],
    reasoning: "Tribal",
    susceptibility: ["Working-class solidarity language", "Anti-corporate rhetoric"],
  },
  {
    name: "Anita Sharma",
    age: 31,
    location: "Parramatta NSW",
    occupation: "Secondary school teacher",
    background: "Indian-Australian migrant. Focused on education, fair wages, and citizenship path.",
    politicalLean: "Progressive",
    concerns: ["Teacher pay", "Immigration pathways", "Housing"],
    reasoning: "Rational",
    susceptibility: ["Education policy depth", "Immigration fairness"],
  },
  {
    name: "Carl Briggs",
    age: 50,
    location: "Tamworth NSW",
    occupation: "Music venue owner",
    background: "Local personality. Lives by tourism and event funding. Feels regions get tokenised.",
    politicalLean: "Swinging",
    concerns: ["Arts and entertainment", "Regional tourism", "Small business"],
    reasoning: "Populist",
    susceptibility: ["Regional acknowledgment", "Blunt authenticity"],
  },
  {
    name: "Susan Fitzgibbon",
    age: 43,
    location: "Hobart TAS",
    occupation: "Marine ecologist",
    background: "Clear-eyed about environmental decline. Calm in argument but deeply committed.",
    politicalLean: "Progressive",
    concerns: ["Climate", "Marine environment", "Science funding"],
    reasoning: "Rational",
    susceptibility: ["Evidence-based argument", "Policy specificity"],
  },
  {
    name: "Robyn Deng",
    age: 56,
    location: "Coffs Harbour NSW",
    occupation: "Real estate agency owner",
    background: "Second-generation Chinese-Australian. Owns investment properties. Believes in hard work.",
    politicalLean: "Conservative",
    concerns: ["Property rights", "Negative gearing", "Business confidence"],
    reasoning: "Rational",
    susceptibility: ["Economic confidence", "Property protection framing"],
  },
  {
    name: "James Okafor",
    age: 36,
    location: "Blacktown NSW",
    occupation: "IT support / Church music director",
    background: "Nigerian-Australian. Concerned about moral decline and cost of raising children.",
    politicalLean: "Conservative-leaning",
    concerns: ["Family values", "Cost of living", "Religious expression"],
    reasoning: "Emotional",
    susceptibility: ["Faith and family framing", "Community values appeals"],
  },
  {
    name: "Penny Albrecht",
    age: 29,
    location: "Margaret River WA",
    occupation: "Winemaker",
    background: "German-Australian. Progressive on climate because of drought impact. Socially liberal.",
    politicalLean: "Progressive",
    concerns: ["Climate", "Agriculture", "Environment"],
    reasoning: "Rational / emotional",
    susceptibility: ["Genuine warmth", "Climate policy", "Regional acknowledgment"],
  },
  {
    name: "Frank Delosa",
    age: 70,
    location: "Leichhardt NSW",
    occupation: "Retired postman",
    background: "Lifelong Labor voter. Genuinely torn for the first time as suburb gentrifies.",
    politicalLean: "Swinging",
    concerns: ["Cost of living", "Community character", "Aged care"],
    reasoning: "Emotional / tribal",
    susceptibility: ["Working-class language", "Community identity appeals"],
  },
  {
    name: "Grace Muir",
    age: 21,
    location: "Perth WA",
    occupation: "Nursing student",
    background: "Working two jobs to pay rent. Wants candidates who make life less hard. Practical.",
    politicalLean: "Swinging",
    concerns: ["Cost of living", "Healthcare", "Student support"],
    reasoning: "Emotional",
    susceptibility: ["Practical cost-of-living relief", "Healthcare investment"],
  },
  {
    name: "Kev Thompson",
    age: 58,
    location: "Bundaberg QLD",
    occupation: "Sugarcane farmer",
    background: "Survived cyclones and drought. Mistrustful of government intervention. Laconic.",
    politicalLean: "Conservative",
    concerns: ["Agriculture", "Disaster relief", "Water", "Climate adaptation"],
    reasoning: "Rational",
    susceptibility: ["Practical climate adaptation", "Respect for farmers"],
  },
  {
    name: "Miriam Gold",
    age: 66,
    location: "St Kilda VIC",
    occupation: "Retired social worker",
    background: "Jewish-Australian progressive voter. Impatient with centrism. Focused on inequality.",
    politicalLean: "Progressive",
    concerns: ["Welfare", "Inequality", "Human rights", "Aged care"],
    reasoning: "Ideological",
    susceptibility: ["Inequality framing", "Progressive values language"],
  },
  {
    name: "Ben Sato",
    age: 27,
    location: "Adelaide SA",
    occupation: "Café owner",
    background: "Japanese-Australian. Obsessively focused on business survival. No time for ideology.",
    politicalLean: "Centre",
    concerns: ["Small business costs", "Interest rates", "Consumer spending"],
    reasoning: "Rational",
    susceptibility: ["Economic stability", "Small business concessions"],
  },
  {
    name: "Colleen Nguyen",
    age: 55,
    location: "Inala QLD",
    occupation: "Aged care worker",
    background: "Vietnamese-Australian. Compassionate and tired. Wants recognition for aged care.",
    politicalLean: "Progressive",
    concerns: ["Aged care", "Worker wages", "Immigration", "Cost of living"],
    reasoning: "Emotional",
    susceptibility: ["Aged care policy specifics", "Frontline worker acknowledgment"],
  },
  {
    name: "Andrew Payne",
    age: 62,
    location: "Manly NSW",
    occupation: "Retired investment banker",
    background: "Fiscally sharp. Conservative by default but concerned about intergenerational fairness.",
    politicalLean: "Centre-right",
    concerns: ["Fiscal policy", "Climate (long-term)", "Superannuation"],
    reasoning: "Rational",
    susceptibility: ["Economic rigour", "Long-term thinking", "Data"],
  },
  {
    name: "Destiny Williams",
    age: 23,
    location: "Redfern NSW",
    occupation: "Social work student",
    background: "Aboriginal Australian university student. Sceptical of mainstream political promises.",
    politicalLean: "Progressive",
    concerns: ["Indigenous rights", "Housing", "Social work funding", "Treaty"],
    reasoning: "Rational / emotional",
    susceptibility: ["Specific Indigenous policy", "Genuine acknowledgment"],
  },
];

export function getRandomVoters(count: number = 21): VoterProfile[] {
  const shuffled = [...VOTER_POOL].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
